events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/react;   # adjust if your build is in /dist or /build
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        gzip off;
    }
}