events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/react;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
	gzip off;
    }




    server {
        listen 81;
        server_name localhost;
	
        root /var/www/html/php/public;
        index index.php;

	location / {
            try_files $uri $uri/ /index.php?_url=$uri&$args;
   	}

    	location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

}